# LambDynamicLights configuration.
# The dynamic lights mode
mode = "none"

 # Light sources settings.
[light_sources]
    # Enable entities light source.
    entities = true
    # Enable block entities light source.
    block_entities = true
